#ifndef PLATFORM_WIN64_H
#define PLATFORM_WIN64_H

#ifdef _WIN64

#include <windows.h>

#define KEY_SPACE VK_SPACE
#define KEY_SHIFT VK_SHIFT
#define KEY_ARROW_LEFT VK_LEFT
#define KEY_ARROW_RIGHT VK_RIGHT
#define KEY_ARROW_UP VK_UP
#define KEY_ARROW_DOWN VK_DOWN
#define KEY_MOUSE_LEFT VK_LBUTTON
#define KEY_MOUSE_RIGHT VK_RBUTTON

#endif

#endif